services:
  redis:
    image: redis:7-alpine

  backend1:
    build: ./backend/ChatServer
    environment:
      - REPLICA_NAME=backend1
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis

  backend2:
    build: ./backend/ChatServer
    environment:
      - REPLICA_NAME=backend2
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis

  backend3:
    build: ./backend/ChatServer
    environment:
      - REPLICA_NAME=backend3
      - REDIS_CONNECTION=redis:6379
    depends_on:
      - redis

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
      - backend3
